apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookly-app

resources:
  - namespace.yaml
  - configmap.yaml
  - configmap-postgres-init.yaml
  - secret.yaml
  - pvc-postgres.yaml
  - pvc-mongo.yaml
  - deployment-postgres.yaml
  - deployment-mongo.yaml
  - deployment-api-core.yaml
  - deployment-api-books.yaml
  - deployment-frontend.yaml
  - service-postgres.yaml
  - service-mongo.yaml
  - service-api-core.yaml
  - service-api-books.yaml
  - service-frontend.yaml
  - ingress.yaml
  - hpa-api-core.yaml
  - hpa-api-books.yaml
  - hpa-frontend.yaml
