apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: bookly-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "booklypwd"
  PGPASSWORD: "booklypwd"
---
# Note: En production, utilisez des outils comme Sealed Secrets, External Secrets Operator,
# ou des services cloud (AWS Secrets Manager, Azure Key Vault, etc.)
