apiVersion: v1
kind: Service
metadata:
  name: api-core
  namespace: bookly-app
  labels:
    app: api-core
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: api-core
