apiVersion: v1
kind: Service
metadata:
  name: api-books
  namespace: bookly-app
  labels:
    app: api-books
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: api-books
